### ISSUE TITLE
Nuvarande kapacitet

### ISSUE THREAD

**Issue by gabgu088** [svrlnd/Kandidatgrupp-4#21]
Räkna på nuvarande kapacitet och lägg in i GUI:n i Uppdragslistan hur kapapciteten är när ett nytt uppdrag har tagits.

**Comment by annda430** [comment]
Jag har börjat, men inte skrivit ut det i uppdragslistan

**Comment by gsedvallson** [comment]
Kapaciteten skrivs nu ut i uppdragslistan, men inte när ett nytt uppdrag har tagits utan hela tiden
