### ISSUE TITLE
Bluetoothkommunikationen på GUI:n

### ISSUE THREAD

**Issue by gabgu088** [svrlnd/Kandidatgrupp-4#22]
På GUI:n ska man hela tiden kunna se hur bluetoothkommuniktionen är/funkar.

**Comment by annda430** [comment]
Om den gröna roboten på skärmen flyttar sig så ser man att det finns kommunikation, räcker det?

**Comment by annda430** [comment]
Min förra kommentar gäller inte längre, vi lär vilja visa på annat sätt att det finns kommunikation
